### ISSUE TITLE
FIX: Google fonts are not working properly

### ISSUE THREAD

**Issue by priyansh1161** [priyansh1161/priyansh1161.github.io#1]
IDK but when font-family is not given Raleway is applied to the whole HTML but not working when applied via CSS i.e `font-family: 'Raleway', sans-serif;`. similarly, Titillium Web is never applied as 
`font-family: 'Titillium Web', sans-serif;` also doesn't work.

Refer: https://github.com/priyansh1161/priyansh1161.github.io/blob/master/index.html#L8
https://github.com/priyansh1161/priyansh1161.github.io/blob/master/main.css#L23

**Comment by Darsh2987** [comment]
Hey Priyansh... take a closer look at line 8 within the HTML, your missing a little bit from the google font link code. Now the reason why your content looks like the "Raleway" font is because the browser is falling back to "San Serif". For now leave line 8 as it is and delete San Serif and see how your content looks. Once you've done that, undo San Serif delete and fix line 8. :-)

**Comment by bhatiatanish** [comment]
Is the issue still open? Assign it to me I can help.

**Comment by Darsh2987** [comment]
Ok maybe I should of asked first if this issue is still open to work on, my apologies... however I did a bit more research and realised that there is another way to fix this issue.You can use @import within the CSS to apply the relevant fonts with the following code below... make sure the code is at the very top of the CSS document before all of the declarations. 

No need for the google font link with the HTML.

I will do a pull request.

@import url('https://fonts.googleapis.com/css?family=Raleway|Titillium+Web');

Thanks

**Comment by priyansh1161** [comment]
@Darsh2987 @bhatiatanish The issue is still open

**Comment by priyansh1161** [comment]
@Darsh2987 Your solution doesn't solve the issue, but you can definitely send a PR of the solved version.
PS: there are no issues in the way I am importing the font in HTML, I have checked that in network tab in chrome

**Comment by jasonwilliams** [comment]
> IDK but when font-family is not given Raleway is applied to the whole HTML but not working when applied via CSS i.e font-family: 'Raleway', sans-serif;

Not for me, i get the default browser font. You just need to un-comment the font-family lines and all should be good, ive noticed 2 PRs, you should accepted @Darsh2987's PR if he took on the ticket first. 

![nofontfamily](https://user-images.githubusercontent.com/936006/31146170-a1676a46-a87d-11e7-8d8b-e8630a8014f4.jpg)
![defaultfont](https://user-images.githubusercontent.com/936006/31146203-bc3adbd2-a87d-11e7-9b35-03678f63cfe5.jpg)
